### ISSUE TITLE
Any airplay 2 support in the works?

### ISSUE THREAD

**Issue by stefanomartinengo** [FD-/RPiPlay#42] opened 2019-11-24 02:31 UTC
This has worked beautifully and perfectly will mirror videos via my plex server. Is there any known info on getting appleTV, netflix, etc. working through the raspberry pi?

**Comment by FD-** [comment] 2019-11-24 09:20
AFAICT, video support is completely unrelated to AirPlay 2. The video protocol is not a different version of the implemented (mirroring) protocol, but an entirely different protocol (though it shares some common functionalities.

**Comment by FD-** [comment] 2019-11-24 09:21
Duplicate of #7

**Closed by FD-** 2019-11-24 09:21 UTC
