### ISSUE TITLE
Is RPiPlay only for mirroring?

### ISSUE THREAD

**Issue by kevintran-git** [FD-/RPiPlay#103] opened 2020-04-26 21:01 UTC
Screen mirroring works for me, however I cannot play any videos using the Airplay button.
The video shows the "Is Airplaying Screen" however the TV is black and the bar cannot progress.
I've tried on other websites too, and no luck.
The screen cast is very fast and responsive.

I'm using an iPad on iOS 13.
```
eport = 46683, tport = 51389
raop_ntp send_len = 32
raop_ntp receive time type_t packetlen = 32
raop_ntp sync correction = -1587729495826034
Accepted IPv4 client on socket 17
Local: 10.0.0.31
Remote: 10.0.0.36
httpd receiving on socket 15
conn_request
Handling request GET with URL /info
INFO len = 1934596308
httpd receiving on socket 15
conn_request
Handling request GET_PARAMETER with URL rtsp://10.0.0.31/14911390288597438254
httpd receiving on socket 15
conn_request
Handling request RECORD with URL rtsp://10.0.0.31/14911390288597438254
raop_handler_record
httpd receiving on socket 15
conn_request
Handling request SET_PARAMETER with URL rtsp://10.0.0.31/14911390288597438254
httpd receiving on socket 15
conn_request
Handling request SET_PARAMETER with URL rtsp://10.0.0.31/14911390288597438254
httpd receiving on socket 15
conn_request
Handling request POST with URL /feedback
raop_handler_feedback
raop_ntp send_len = 32
raop_ntp receive timeout
raop_ntp exiting thread
httpd receiving on socket 15
conn_request
Handling request POST with URL /feedback
raop_handler_feedback
httpd receiving on socket 15
conn_request
Handling request POST with URL /feedback
raop_handler_feedback
httpd receiving on socket 15
conn_request
Handling request POST with URL /feedback
raop_handler_feedback
httpd receiving on socket 17
Connection closed for socket 17
Destroying connection```

**Comment by FD-** [comment] 2020-04-27 07:12
Search open issues before filing a new one. This is a duplicate of https://github.com/FD-/RPiPlay/issues/7

**Closed by FD-** 2020-04-27 07:12 UTC
