### ISSUE TITLE
RTSP H264 feed to ffmpeg

### ISSUE THREAD

**Issue by saket424** [FD-/RPiPlay#48] opened 2019-12-12 13:42 UTC
Thanks for this amazing opensource project. I was wondering if instead of rendering the feed locally on the pi, the h264 rtsp video feed that is negotiated during the mirroring is available to something like ffmpeg to send to a remote RTMP/RTSP server .

Thoughts?

**Comment by FD-** [comment] 2019-12-12 13:46
Not at the moment, but it should be easy to do, as sketched in #24.

**Comment by saket424** [comment] 2019-12-12 14:09
If this https://nto.github.io/AirPlay.html#screenmirroring is still accurate, video screen mirroring is a TCP connection sending the H264 payload directly over a TCP connection and not via RTSP.

I will explore it in the coming days and see how we may be able to get the payload sent over to ffmpeg. Thanks

**Comment by FD-** [comment] 2019-12-12 14:39
Sorry, I thought you wanted to just pipe the raw H264 stream out of RPiPlay. I'm not sure how you'd convert that into an RTSP stream, but I assume there must be some tool capable of doing that. The AirPlay protocol itself doesn't involve an RTSP stream that could be simply rerouted.

**Comment by FD-** [comment] 2020-01-02 09:54
Duplicate of #24

**Closed by FD-** 2020-01-02 09:54 UTC
