### ISSUE TITLE
YouTube not streaming video 

### ISSUE THREAD

**Issue by thomas192000** [FD-/RPiPlay#44] opened 2019-11-30 20:30 UTC
If i want to stream a video from YouTube from my iPhone to thé raspberry, the loading screen remains. I can't see a video on the Raspberry pi 3

**Comment by FD-** [comment] 2019-11-30 20:31
A known issue linked to #7 .

**Comment by FD-** [comment] 2019-11-30 20:31
Duplicate of #7

**Closed by FD-** 2019-11-30 20:31 UTC
