### ISSUE TITLE
aacDecoder DecodeFrame error

### ISSUE THREAD

**Issue by loricheung** [FD-/RPiPlay#12] opened 2019-08-23 19:18 UTC
Hi, I build it on raspberry 3B+, but when I play music from iphone X (iOS 13 beta), it got this error

> Accepted IPv4 client on socket 15
> Local: 192.168.11.151
> Remote: 192.168.11.235
> Accepted IPv4 client on socket 17
> Local: 192.168.11.151
> Remote: 192.168.11.235
> raop_rtp starting audio
> Got image data of 87061 bytes
> raop_ntp receive timeout
> raop_rtp starting audio
> Got image data of 87061 bytes
> Got metadata of 162 bytes
> Got metadata of 141 bytes
> aacDecoder_DecodeFrame error : 0x4002
> aacDecoder_DecodeFrame error : 0x400c
> aacDecoder_DecodeFrame error : 0x400c
> aacDecoder_DecodeFrame error : 0x400c
> aacDecoder_DecodeFrame error : 0x400c
> Got image data of 87061 bytes
> Got metadata of 162 bytes
> aacDecoder_DecodeFrame error : 0x4002
> Got metadata of 129 bytes
> Got metadata of 129 bytes

and when I using iphone 6s (iOS 12.4), it got this error

> Initialized server socket(s)
*** WARNING *** The program 'rpiplay' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
Accepted IPv4 client on socket 15
Local: 192.168.11.151
Remote: 192.168.11.131
Accepted IPv4 client on socket 17
Local: 192.168.11.151
Remote: 192.168.11.131
raop_rtp starting audio
aacDecoder_DecodeFrame error : 0x5
rpiplay: malloc.c:2385: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
[1]    5147 abort      ./rpiplay

**Comment by FD-** [comment] 2019-08-24 11:32
Duplicate of #2.

**Closed by FD-** 2019-08-24 11:32 UTC
Labels: duplicate
