### ISSUE TITLE
Can't reconnect

### ISSUE THREAD

**Issue by TommySchwartz** [FD-/RPiPlay#14] opened 2019-08-31 19:43 UTC
I can only connect and mirror screen one time (works great!). 
Connecting the second time only shows black screen.

if I want to reconnect I have to restart RPiPlay to be able to mirror again.

Don't know where and how to debug, but please provide directions and I will try my best.

**Comment by duartesaraiiva** [comment] 2019-08-31 22:45
Having the same problem

**Comment by FD-** [comment] 2019-09-01 16:12
For a useful bug report, please include the following:

* Steps to reliably reproduce the problem
* The (debug) output of RPiPlay at the time of malfunction

Please test if undoing the latest commit (commit 3449d878) fixes the issue.

**Comment by duartesaraiiva** [comment] 2019-09-01 19:08
Start the rpiplay, then connect, disconnect and reconnect. THe 2nd time it will fail.
For me, if i use the "-b" arg fixes this error

Debug code without the "-b" flag:
`> stream info: channel = 2	sample_rate = 44100	frame_size = 480	aot = 39	bitrate = 0
Initialized server socket(s)
*** WARNING *** The program 'rpiplay' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
Accepted IPv4 client on socket 15
Local: 192.168.1.144
Remote: 192.168.1.140
httpd receiving on socket 15
conn_request
Handling request GET with URL /info
INFO len = 1933547732
httpd receiving on socket 15
conn_request
Handling request POST with URL /pair-setup
httpd receiving on socket 15
conn_request
Handling request POST with URL /pair-verify
httpd receiving on socket 15
conn_request
Handling request POST with URL /pair-verify
httpd receiving on socket 15
conn_request
Handling request POST with URL /fp-setup
httpd receiving on socket 15
conn_request
Handling request POST with URL /fp-setup
httpd receiving on socket 15
conn_request
Handling request SETUP with URL rtsp://192.168.1.144/3899814181647565792
DACP-ID: 446194CE3E1F8F37
Active-Remote: 1363207522
Transport: null
SETUP 1
eiv_len = 16
ekey_len = 72
fairplay_decrypt ret = 0
timing_rport = 52137
raop_ntp parse remote ip = 192.168.1.140
raop_ntp starting time
raop_rtp parse remote ip = 192.168.1.140
raop_rtp_mirror parse remote ip = 192.168.1.140
raop_ntp send_len = 32
eport = 42767, tport = 55225
raop_ntp receive time type_t packetlen = 32
raop_ntp sync correction = -1567353558529908
Accepted IPv4 client on socket 17
Local: 192.168.1.144
Remote: 192.168.1.140
httpd receiving on socket 15
conn_request
Handling request GET with URL /info
INFO len = 1933547732
httpd receiving on socket 15
conn_request
Handling request GET_PARAMETER with URL rtsp://192.168.1.144/3899814181647565792
httpd receiving on socket 15
conn_request
Handling request RECORD with URL rtsp://192.168.1.144/3899814181647565792
raop_handler_record
httpd receiving on socket 15
conn_request
Handling request SET_PARAMETER with URL rtsp://192.168.1.144/3899814181647565792
httpd receiving on socket 15
conn_request
Handling request SETUP with URL rtsp://192.168.1.144/3899814181647565792
DACP-ID: 446194CE3E1F8F37
Active-Remote: 1363207522
Transport: null
type = 110
streamConnectionID = 16210094761558819460
raop_rtp_mirror starting mirroring
Mirroring initialized successfully
httpd receiving on socket 15
conn_request
Handling request SET_PARAMETER with URL rtsp://192.168.1.144/3899814181647565792
raop_rtp_mirror accepting client
raop_rtp_mirror width_source = 546.000000 height_source = 972.000000 width = 570.000000 height = 1016.000000
raop_rtp_mirror sps size = 18
raop_rtp_mirror pps size = 4
Got h264 data of 30 bytes
Injecting max_dec_frame_buffering
Video delay is 1567363581771980
raop_rtp_mirror video ntp = 1567363581745841, now = 1567363581772205, latency = 26364
Got h264 data of 4804 bytes
Video delay is 27129
raop_rtp_mirror video ntp = 1567363581795844, now = 1567363581773101, latency = -22743
Got h264 data of 400 bytes
Video delay is -22336
raop_rtp_mirror video ntp = 1567363581812511, now = 1567363581773579, latency = -38932
Got h264 data of 3183 bytes
Video delay is -38192
raop_rtp_mirror video ntp = 1567363581845847, now = 1567363581774396, latency = -71451
Got h264 data of 253 bytes
Video delay is -71114
raop_rtp_mirror video ntp = 1567363581862515, now = 1567363581788901, latency = -73614
Got h264 data of 1687 bytes
Port settings changed!!
Video pipeline delay is 6 frames or 18975 us
Video delay is -68757
raop_rtp_mirror video ntp = 1567363581879183, now = 1567363581806065, latency = -73118
Got h264 data of 4767 bytes
Video delay is -71719
raop_rtp_mirror video ntp = 1567363581895850, now = 1567363581820687, latency = -75163
Got h264 data of 2176 bytes
Video delay is -65056
raop_rtp_mirror video ntp = 1567363581912518, now = 1567363581835526, latency = -76992
Got h264 data of 1930 bytes
Video delay is -76015
raop_rtp_mirror video ntp = 1567363581929186, now = 1567363581851988, latency = -77198
Got h264 data of 2457 bytes
Video delay is -76446
raop_rtp_mirror video ntp = 1567363581945854, now = 1567363581871601, latency = -74253
Got h264 data of 8496 bytes
Video delay is -72933
raop_rtp_mirror video ntp = 1567363581962521, now = 1567363581886172, latency = -76349
Got h264 data of 8476 bytes
Video delay is -75163
raop_rtp_mirror video ntp = 1567363581979189, now = 1567363581910621, latency = -68568
Got h264 data of 9626 bytes
Video delay is -67263
raop_rtp_mirror video ntp = 1567363581995857, now = 1567363581920413, latency = -75444
Got h264 data of 12522 bytes
Video delay is -73929
raop_rtp_mirror video ntp = 1567363582012525, now = 1567363581938071, latency = -74454
Got h264 data of 11904 bytes
Video delay is -72945
raop_rtp_mirror video ntp = 1567363582029192, now = 1567363581958770, latency = -70422
Got h264 data of 11506 bytes
Video delay is -69142
raop_rtp_mirror video ntp = 1567363582045860, now = 1567363581972023, latency = -73837
Got h264 data of 10089 bytes
Video delay is -72365
raop_rtp_mirror video ntp = 1567363582062528, now = 1567363581984887, latency = -77641
Got h264 data of 9711 bytes
Video delay is -76369
raop_rtp_mirror video ntp = 1567363582079196, now = 1567363582003411, latency = -75785
Got h264 data of 9093 bytes
Video delay is -74224
raop_rtp_mirror video ntp = 1567363582095863, now = 1567363582018489, latency = -77374
Got h264 data of 9139 bytes
Video delay is -76298
raop_rtp_mirror video ntp = 1567363582112531, now = 1567363582036335, latency = -76196
Got h264 data of 8828 bytes
Video delay is -74914
raop_rtp_mirror video ntp = 1567363582129199, now = 1567363582166439, latency = 37240
Got h264 data of 8411 bytes
Video delay is 38364
raop_rtp_mirror video ntp = 1567363582145867, now = 1567363582167742, latency = 21875
Got h264 data of 5363 bytes
Video delay is 22635
raop_rtp_mirror video ntp = 1567363582162534, now = 1567363582168572, latency = 6038
Got h264 data of 2378 bytes
Video delay is 6628
raop_rtp_mirror video ntp = 1567363582179201, now = 1567363582169219, latency = -9982
Got h264 data of 2058 bytes
Video delay is -9465
raop_rtp_mirror video ntp = 1567363582195868, now = 1567363582169805, latency = -26063
Got h264 data of 1907 bytes
Video delay is -25535
raop_rtp_mirror video ntp = 1567363582212534, now = 1567363582176225, latency = -36309
Got h264 data of 1819 bytes
Video delay is -35738
httpd receiving on socket 15
conn_request
Handling request POST with URL /feedback
raop_handler_feedback
raop_rtp_mirror video ntp = 1567363583729303, now = 1567363583658358, latency = -70945
Got h264 data of 1792 bytes
Video delay is -70310
raop_rtp_mirror video ntp = 1567363583745970, now = 1567363583706373, latency = -39597
Got h264 data of 1792 bytes
Video delay is -38874
raop_rtp_mirror video ntp = 1567363583762636, now = 1567363583720357, latency = -42279
Got h264 data of 1792 bytes
Video delay is -41537
raop_rtp_mirror video ntp = 1567363583779303, now = 1567363583739814, latency = -39489
Got h264 data of 1792 bytes
Video delay is -38835
raop_ntp send_len = 32
raop_ntp receive timeout
raop_ntp exiting thread
httpd receiving on socket 15
conn_request
Handling request POST with URL /feedback
raop_handler_feedback
raop_rtp_mirror video ntp = 1567363586012785, now = 1567363585953002, latency = -59783
Got h264 data of 2150 bytes
Video delay is -58915
raop_rtp_mirror video ntp = 1567363586029451, now = 1567363586007321, latency = -22130
Got h264 data of 1854 bytes
Video delay is -21138
raop_rtp_mirror video ntp = 1567363586046118, now = 1567363586028171, latency = -17947
Got h264 data of 1805 bytes
Video delay is -16943
raop_rtp_mirror video ntp = 1567363586062785, now = 1567363586034059, latency = -28726
Got h264 data of 1799 bytes
Video delay is -27774
raop_rtp_mirror video ntp = 1567363586546153, now = 1567363586478559, latency = -67594
Got h264 data of 6376 bytes
Video delay is -66551
httpd receiving on socket 15
conn_request
Handling request SET_PARAMETER with URL rtsp://192.168.1.144/3899814181647565792
raop_rtp_mirror video ntp = 1567363586579488, now = 1567363586503869, latency = -75619
Got h264 data of 6464 bytes
Video delay is -74580
raop_rtp_mirror tcp socket closed
httpd receiving on socket 15
conn_request
Handling request TEARDOWN with URL rtsp://192.168.1.144/3899814181647565792
raop_rtp_mirror exiting TCP thread
httpd receiving on socket 15
conn_request
Handling request TEARDOWN with URL rtsp://192.168.1.144/3899814181647565792
httpd receiving on socket 15
Connection closed for socket 15
Destroying connection
httpd receiving on socket 17
Connection closed for socket 17
Destroying connection
Accepted IPv4 client on socket 15
Local: 192.168.1.144
Remote: 192.168.1.140
httpd receiving on socket 15
conn_request
Handling request GET with URL /info
INFO len = 1933547732
httpd receiving on socket 15
conn_request
Handling request POST with URL /pair-verify
httpd receiving on socket 15
conn_request
Handling request POST with URL /pair-setup
httpd receiving on socket 15
conn_request
Handling request POST with URL /pair-verify
httpd receiving on socket 15
conn_request
Handling request POST with URL /pair-verify
httpd receiving on socket 15
conn_request
Handling request POST with URL /fp-setup
httpd receiving on socket 15
conn_request
Handling request POST with URL /fp-setup
httpd receiving on socket 15
conn_request
Handling request SETUP with URL rtsp://192.168.1.144/11966295245646678080
DACP-ID: 807E1C621AAFC180
Active-Remote: 2439644691
Transport: null
SETUP 1
eiv_len = 16
ekey_len = 72
fairplay_decrypt ret = 0
timing_rport = 52057
raop_ntp parse remote ip = 192.168.1.140
raop_ntp starting time
raop_rtp parse remote ip = 192.168.1.140
raop_ntp send_len = 32
raop_rtp_mirror parse remote ip = 192.168.1.140
eport = 42767, tport = 60242
raop_ntp receive time type_t packetlen = 32
raop_ntp sync correction = -1567353558529383
Accepted IPv4 client on socket 18
Local: 192.168.1.144
Remote: 192.168.1.140
httpd receiving on socket 15
conn_request
Handling request GET with URL /info
INFO len = 1933547732
httpd receiving on socket 15
conn_request
Handling request GET_PARAMETER with URL rtsp://192.168.1.144/11966295245646678080
httpd receiving on socket 15
conn_request
Handling request RECORD with URL rtsp://192.168.1.144/11966295245646678080
raop_handler_record
httpd receiving on socket 15
conn_request
Handling request SET_PARAMETER with URL rtsp://192.168.1.144/11966295245646678080
httpd receiving on socket 15
conn_request
Handling request SETUP with URL rtsp://192.168.1.144/11966295245646678080
DACP-ID: 807E1C621AAFC180
Active-Remote: 2439644691
Transport: null
type = 110
streamConnectionID = 17745353957623286752
raop_rtp_mirror starting mirroring
Mirroring initialized successfully
httpd receiving on socket 15
conn_request
Handling request SET_PARAMETER with URL rtsp://192.168.1.144/11966295245646678080
raop_rtp_mirror accepting client
raop_rtp_mirror width_source = 546.000000 height_source = 972.000000 width = 570.000000 height = 1016.000000
raop_rtp_mirror sps size = 18
raop_rtp_mirror pps size = 4
Got h264 data of 30 bytes
Injecting max_dec_frame_buffering
Video delay is 1567363591358499
raop_rtp_mirror video ntp = 1567363591395859, now = 1567363591358768, latency = -37091
Got h264 data of 4801 bytes
Video delay is -36185
raop_rtp_mirror video ntp = 1567363591412526, now = 1567363591365778, latency = -46748
Got h264 data of 731 bytes
Video delay is -46087
raop_rtp_mirror video ntp = 1567363591429193, now = 1567363591382787, latency = -46406
Got h264 data of 2867 bytes
Video delay is -45455
raop_rtp_mirror video ntp = 1567363591479198, now = 1567363591397509, latency = -81689
Got h264 data of 873 bytes
Video delay is -80878
raop_rtp_mirror video ntp = 1567363591495865, now = 1567363591452289, latency = -43576
Got h264 data of 3691 bytes
Video delay is -42591
raop_rtp_mirror video ntp = 1567363591512531, now = 1567363591465401, latency = -47130
Got h264 data of 4787 bytes
Video delay is -46184
raop_rtp_mirror video ntp = 1567363591545869, now = 1567363591473570, latency = -72299
Got h264 data of 6384 bytes
Video delay is -71094
raop_rtp_mirror video ntp = 1567363591562537, now = 1567363591591194, latency = 28657
Got h264 data of 2964 bytes
Video delay is 29637
raop_rtp_mirror video ntp = 1567363591579205, now = 1567363591592492, latency = 13287
Got h264 data of 3450 bytes
Video delay is 14230
raop_rtp_mirror video ntp = 1567363591595872, now = 1567363591593522, latency = -2350
Got h264 data of 3284 bytes
Video delay is -1339
raop_rtp_mirror video ntp = 1567363591612540, now = 1567363591594655, latency = -17885
Got h264 data of 9372 bytes
Video delay is -16761
raop_rtp_mirror video ntp = 1567363591629208, now = 1567363591595883, latency = -33325
Got h264 data of 4548 bytes
Video delay is -32579
raop_rtp_mirror video ntp = 1567363591645876, now = 1567363591603912, latency = -41964
Got h264 data of 11583 bytes
Video delay is -40307
raop_rtp_mirror video ntp = 1567363591662543, now = 1567363591609638, latency = -52905
Got h264 data of 11577 bytes
Video delay is -51007
raop_rtp_mirror video ntp = 1567363591679211, now = 1567363591611845, latency = -67366
Got h264 data of 11879 bytes
Video delay is -66180
raop_rtp_mirror video ntp = 1567363591695879, now = 1567363591727014, latency = 31135
Got h264 data of 10886 bytes
Video delay is 32471
raop_rtp_mirror video ntp = 1567363591712547, now = 1567363591728513, latency = 15966
Got h264 data of 11018 bytes
Video delay is 17181
raop_rtp_mirror video ntp = 1567363591729214, now = 1567363591737819, latency = 8605
Got h264 data of 9758 bytes
Video delay is 9838
raop_rtp_mirror video ntp = 1567363591745882, now = 1567363591740378, latency = -5504
Got h264 data of 8925 bytes
Video delay is -4309
raop_rtp_mirror video ntp = 1567363591762550, now = 1567363591744468, latency = -18082
Got h264 data of 8353 bytes
Video delay is -16710
raop_rtp_mirror video ntp = 1567363591779218, now = 1567363591746082, latency = -33136
Got h264 data of 8590 bytes
Video delay is -31910
raop_rtp_mirror video ntp = 1567363591795885, now = 1567363591751576, latency = -44309
Got h264 data of 8938 bytes
Video delay is -43194
raop_rtp_mirror video ntp = 1567363591812553, now = 1567363591798810, latency = -13743
Got h264 data of 8132 bytes
Video delay is -12618
raop_rtp_mirror video ntp = 1567363591829221, now = 1567363591800074, latency = -29147
Got h264 data of 2845 bytes
Video delay is -28456
raop_rtp_mirror video ntp = 1567363591845889, now = 1567363591800870, latency = -45019
Got h264 data of 2194 bytes
Video delay is -44394
raop_rtp_mirror video ntp = 1567363591862555, now = 1567363591822666, latency = -39889
Got h264 data of 1912 bytes
Video delay is -39079
raop_rtp_mirror video ntp = 1567363591879222, now = 1567363591835186, latency = -44036
Got h264 data of 1816 bytes
Video delay is -43284
raop_rtp_mirror video ntp = 1567363591895889, now = 1567363591852387, latency = -43502
Got h264 data of 1789 bytes
Video delay is -42500
raop_rtp_mirror video ntp = 1567363593245980, now = 1567363593177553, latency = -68427
Got h264 data of 1789 bytes
Video delay is -67651
raop_rtp_mirror video ntp = 1567363593262646, now = 1567363593294821, latency = 32175
Got h264 data of 1789 bytes
Video delay is 33022
raop_rtp_mirror video ntp = 1567363593279313, now = 1567363593295794, latency = 16481
Got h264 data of 1791 bytes
Video delay is 17173
raop_rtp_mirror video ntp = 1567363593295980, now = 1567363593296658, latency = 678
httpd receiving on socket 15
Got h264 data of 1790 bytes
conn_request
Handling request POST with URL /feedback
raop_handler_feedback
Video delay is 1324
raop_rtp_mirror video ntp = 1567363593379322, now = 1567363593301176, latency = -78146
Got h264 data of 1789 bytes
Video delay is -77450
raop_rtp_mirror video ntp = 1567363593395988, now = 1567363593354774, latency = -41214
Got h264 data of 1789 bytes
Video delay is -40219
raop_rtp_mirror video ntp = 1567363593412655, now = 1567363593370300, latency = -42355
Got h264 data of 1789 bytes
Video delay is -41587
raop_rtp_mirror video ntp = 1567363593429322, now = 1567363593387466, latency = -41856
Got h264 data of 1789 bytes
Video delay is -41091
raop_rtp_mirror video ntp = 1567363593946025, now = 1567363593873204, latency = -72821
Got h264 data of 5317 bytes
Video delay is -71736
httpd receiving on socket 15
conn_request
Handling request SET_PARAMETER with URL rtsp://192.168.1.144/11966295245646678080
raop_rtp_mirror video ntp = 1567363593979361, now = 1567363593903401, latency = -75960
Got h264 data of 5561 bytes
Video delay is -74926
raop_rtp_mirror tcp socket closed
httpd receiving on socket 15
conn_request
Handling request TEARDOWN with URL rtsp://192.168.1.144/11966295245646678080
raop_rtp_mirror exiting TCP thread
httpd receiving on socket 15
conn_request
Handling request TEARDOWN with URL rtsp://192.168.1.144/11966295245646678080
httpd receiving on socket 18
Connection closed for socket 18
Destroying connection
httpd receiving on socket 15
Connection closed for socket 15
Destroying connection
raop_ntp stopping time thread
raop_ntp exiting thread
raop_ntp stopped time thread
Stopping...
`
Undoing to the commit [https://github.com/FD-/RPiPlay/commit/77ffeffa994bf356e320006dbfe7523cc81eb695](77ffeff) works but when I stop the projection the last frame keeps until reconnect again

**Comment by FD-** [comment] 2019-09-03 09:21
Please let me know if the latest commit fixes the issue.

**Comment by TommySchwartz** [comment] 2019-09-03 11:15
I get a compiler error when running make: "no member named 'hidden'".

`[ 98%] Building C object renderers/CMakeFiles/renderers.dir/video_renderer_rpi.c.o
/home/pi/RPiPlay/renderers/video_renderer_rpi.c: In function ‘video_renderer_init’:
/home/pi/RPiPlay/renderers/video_renderer_rpi.c:282:13: error: ‘video_renderer_’ {aka ‘struct video_renderer_s’} has no member named ‘hidden’
     renderer->hidden = false;
             ^~
make[2]: *** [renderers/CMakeFiles/renderers.dir/build.make:76: renderers/CMakeFiles/renderers.dir/video_renderer_rpi.c.o] Fel 1
make[1]: *** [CMakeFiles/Makefile2:465: renderers/CMakeFiles/renderers.dir/all] Fel 2
make: *** [Makefile:84: all] Fel 2`

**Comment by TommySchwartz** [comment] 2019-09-03 11:47
Added under struct video_renderers_s
`bool hidden;`
just to see if it compiled, and it does.

Now RPiPlay reconnects as expected!
Bonus is that I now can switch between duplicate/extended display settings without any trouble. 
Thank you!

**Comment by FD-** [comment] 2019-09-03 12:46
Oh, seems like I only committed some of the changes I intended to. Should be fixed now.

**Comment by duartesaraiiva** [comment] 2019-09-03 13:21
Tested and confirm it’s working

**Comment by FD-** [comment] 2019-09-03 14:09
I just committed a cleaner fix, so please test that as well. Also, probably an even cleaner solution might be possible, depending of the result of the [discussion in the Raspberry Pi forums](https://www.raspberrypi.org/forums/viewtopic.php?p=1530307#p1530307).

**Comment by TommySchwartz** [comment] 2019-09-03 14:32
Works!

**Comment by FD-** [comment] 2019-09-03 14:39
Thanks for the confirmation! According to 6by9 in the forum, the current implementation is the expected way to do things, so I'll close this issue now.

**Closed by FD-** 2019-09-03 14:39 UTC
Labels: bug, fix confirmation needed
