### ISSUE TITLE
No works in Rasp Pi 4B

### ISSUE THREAD

**Issue by victorsnk** [FD-/RPiPlay#123] opened 2020-05-23 16:42 UTC
I have followed the steps. I have a Raspberry Pi 4B 4GB. It doesn't work for me. Is this model compatible? Thank you.
![photo_2020-05-23_16-41-30](https://user-images.githubusercontent.com/32032710/82735857-277bd880-9d25-11ea-9694-119fb8eaf0d8.jpg)

**Comment by FD-** [comment] 2020-05-25 11:00
Duplicate of #2

**Closed by FD-** 2020-05-25 11:00 UTC
