### ISSUE TITLE
Problem with cmake

### ISSUE THREAD

**Issue by sorriso93** [FD-/RPiPlay#75] opened 2020-03-06 20:20 UTC
Hello
followed the instruction to compile but I get this error:

root@RASPB3DIETPI:/home/RPiPlay/build# sudo cmake ..
-- Configuring done
CMake Error at renderers/CMakeLists.txt:26 (add_library):
  No SOURCES given to target: ilclient

-- Build files have been written to: /home/RPiPlay

what is ilclient?
many thks

**Comment by FD-** [comment] 2020-03-06 20:26
I only support running this on Raspbian. For every other OS you’re on your own. Closing as duplicate of #10

**Closed by FD-** 2020-03-06 20:26 UTC
