### ISSUE TITLE
Videos do not play from phone

### ISSUE THREAD

**Issue by krushanu** [FD-/RPiPlay#74] opened 2020-02-29 17:30 UTC
When I an casting from my iPhone, and swiping on the screen and open any app, there is no problem.
in fact, Facebook and videos on Facebook also work fine.
BUT.
When I play a video on youtube or Netflix. the strimming just stopes as if there is no internet.

Browsing is fine.

Please help me to cast Netflix and youtube as well. It will help me a lot .. 
Thanks..

**Comment by krushanu** [comment] 2020-02-29 17:30
Gr8 work though 
Really appreciate it.

**Comment by FD-** [comment] 2020-02-29 18:04
Duplicate of #7

**Closed by FD-** 2020-02-29 18:04 UTC
